services:
  trading-bot:
    build: .
    container_name: scalping-trading-bot
    ports:
      - "5002:5002"
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - SYMBOL=${SYMBOL:-BTCUSDT}
      - QUANTITY=${QUANTITY:-0.001}
      - PROFIT_TARGET=${PROFIT_TARGET:-0.003}
      - STOP_LOSS=${STOP_LOSS:-0.002}
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: trading-bot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data: